import Foundation

struct Contradiction: Identifiable, Codable {
    let id: UUID
    let topic: String
    let stageA: Int
    let stageB: Int
    let description: String

    init(topic: String, stageA: Int, stageB: Int, description: String) {
        self.id = UUID()
        self.topic = topic
        self.stageA = stageA
        self.stageB = stageB
        self.description = description
    }
}

struct AnalysisResponse: Decodable {
    let consistencySummary: String
    let hallucinationRisk: String
    let confidenceLevel: String
    let confidenceScore: Double?
    let contradictions: [AnalysisContradiction]
    /// Dynamic analyst-style bullet points generated by the analysis LLM
    let analysisBullets: [String]?

    struct AnalysisContradiction: Decodable {
        let topic: String
        let stageA: Int
        let stageB: Int
        let description: String
    }
}

struct VerificationSummary: Codable {
    let consistency: String
    let hallucinations: String
    let confidence: String
    let contradictions: [Contradiction]
    let confidenceScore: Double?
    let isAnalyzed: Bool
    /// Dynamic analyst-style bullet points summarizing the verification verdict
    let analysisBullets: [String]

    init(
        consistency: String,
        hallucinations: String,
        confidence: String,
        contradictions: [Contradiction] = [],
        confidenceScore: Double? = nil,
        isAnalyzed: Bool = false,
        analysisBullets: [String] = []
    ) {
        self.consistency = consistency
        self.hallucinations = hallucinations
        self.confidence = confidence
        self.contradictions = contradictions
        self.confidenceScore = confidenceScore
        self.isAnalyzed = isAnalyzed
        self.analysisBullets = analysisBullets
    }

    /// Custom decoder to handle history items saved before analysisBullets was added
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        consistency = try container.decode(String.self, forKey: .consistency)
        hallucinations = try container.decode(String.self, forKey: .hallucinations)
        confidence = try container.decode(String.self, forKey: .confidence)
        contradictions = try container.decode([Contradiction].self, forKey: .contradictions)
        confidenceScore = try container.decodeIfPresent(Double.self, forKey: .confidenceScore)
        isAnalyzed = try container.decode(Bool.self, forKey: .isAnalyzed)
        analysisBullets = try container.decodeIfPresent([String].self, forKey: .analysisBullets) ?? []
    }
}
