import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { type VerificationSummary as VerificationSummaryType } from "@shared/schema";

interface VerificationSummaryProps {
  summary: VerificationSummaryType;
}

function getConfidenceBarColor(score?: number): string {
  if (score === undefined) return "bg-muted-foreground";
  if (score >= 0.8) return "bg-green-500";
  if (score >= 0.5) return "bg-yellow-500";
  return "bg-red-500";
}

export function VerificationSummary({ summary }: VerificationSummaryProps) {
  // Controls the fade-in animation when the summary appears
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    // Trigger fade-in on mount
    const timer = setTimeout(() => setIsVisible(true), 50);
    return () => clearTimeout(timer);
  }, []);

  return (
    <motion.div
      className="mt-10 pt-6 border-t-2 border-primary/30 space-y-3"
      data-testid="verification-summary"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <div className="flex items-center gap-2">
        <span className="text-sm font-medium text-primary">VERIFICATION SUMMARY</span>
        {summary.isAnalyzed && (
          <span className="text-xs text-primary opacity-70">[ANALYZED]</span>
        )}
      </div>

      <div className="grid grid-cols-[auto_1fr] gap-x-4 gap-y-3 text-sm py-3">
        <span className="text-muted-foreground whitespace-nowrap">Consistency:</span>
        <span className="text-foreground">{summary.consistency}</span>

        <span className="text-muted-foreground whitespace-nowrap">Hallucinations:</span>
        <span className="text-foreground">{summary.hallucinations}</span>

        <span className="text-muted-foreground whitespace-nowrap">Confidence:</span>
        <span className="text-foreground">{summary.confidence}</span>

        {summary.confidenceScore !== undefined && (
          <div className="mt-1 col-span-2">
            <div className="h-1.5 bg-muted rounded-sm overflow-hidden">
              <div
                className={`h-full ${getConfidenceBarColor(summary.confidenceScore)} transition-all duration-500`}
                style={{ width: `${Math.round(summary.confidenceScore * 100)}%` }}
              />
            </div>
          </div>
        )}
      </div>

      {/* Dynamic analyst-style bullet points — query-specific verdicts
          generated by the analysis LLM or built from pipeline metadata */}
      {summary.analysisBullets && summary.analysisBullets.length > 0 && (
        <div className="space-y-2.5 pt-1">
          {summary.analysisBullets.map((bullet, index) => (
            <motion.div
              key={index}
              className="flex items-start gap-2.5 text-sm"
              initial={{ opacity: 0, y: 6 }}
              animate={isVisible ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.4, delay: index * 0.12 }}
            >
              <span className="text-primary/60 shrink-0">&rsaquo;</span>
              <span className="text-foreground/85">{bullet}</span>
            </motion.div>
          ))}
        </div>
      )}

      {summary.contradictions && summary.contradictions.length > 0 && (
        <div className="space-y-2 pt-2">
          <div className="text-xs font-medium text-destructive">
            DISAGREEMENTS ({summary.contradictions.length})
          </div>
          {summary.contradictions.map((c, i) => (
            <div key={i} className="text-xs space-y-0.5">
              <span className="text-destructive/80">{c.topic}</span>
              <span className="text-muted-foreground ml-1">
                (Stage {c.stageA} vs {c.stageB})
              </span>
              <div className="text-muted-foreground">{c.description}</div>
            </div>
          ))}
        </div>
      )}
    </motion.div>
  );
}
